package de.teamlapen.vampirism.processor.generator;

import de.teamlapen.vampirism.processor.CreatureModel;
import de.teamlapen.vampirism.processor.ProcessorUtil;

/**
 * Generates the abstract {@code Converted<Name>} base class for a single converted creature.
 *
 * <p>The generated class extends the vanilla entity, implements {@code CurableConvertedCreature},
 * and wires all boilerplate lifecycle methods to the extension hooks ({@code *C()} methods).
 * When no {@link de.teamlapen.vampirism.annotation.ConvertedCreature#subclass()} is provided it also carries
 * {@code getAttributeBuilder()} and {@code checkSpawnRules()} statics.
 */
public final class ConvertedEntityClassGenerator {

    private static final String CURABLE = "de.teamlapen.vampirism.common.world.entity.converted.CurableConvertedCreature";

    private ConvertedEntityClassGenerator() {}

    public static String generate(CreatureModel m) {
        StringBuilder im = new StringBuilder();
        ProcessorUtil.imports(im,
                m.baseFqn(), CURABLE,
                "de.teamlapen.vampirism.common.config.BalanceMobProps",
                "de.teamlapen.vampirism.common.core.ModAttributes",
                "net.minecraft.core.BlockPos",
                "net.minecraft.network.chat.Component",
                "net.minecraft.network.syncher.EntityDataAccessor",
                "net.minecraft.network.syncher.EntityDataSerializers",
                "net.minecraft.network.syncher.SynchedEntityData",
                "net.minecraft.server.level.ServerLevel",
                "net.minecraft.util.RandomSource",
                "net.minecraft.world.Difficulty",
                "net.minecraft.world.InteractionHand",
                "net.minecraft.world.InteractionResult",
                "net.minecraft.world.damagesource.DamageSource",
                "net.minecraft.world.entity.EntitySpawnReason",
                "net.minecraft.world.entity.EntityType",
                "net.minecraft.world.entity.ai.attributes.AttributeSupplier",
                "net.minecraft.world.entity.ai.attributes.Attributes",
                "net.minecraft.world.entity.animal.Animal",
                "net.minecraft.world.entity.player.Player",
                "net.minecraft.world.level.Level",
                "net.minecraft.world.level.LevelAccessor",
                "net.minecraft.world.level.storage.ValueInput",
                "net.minecraft.world.level.storage.ValueOutput",
                "org.jetbrains.annotations.NotNull");

        String statics = """
                        public static AttributeSupplier.@NotNull Builder getAttributeBuilder() {
                            return %1$s.%2$s().add(Attributes.ATTACK_DAMAGE, BalanceMobProps.mobProps.CONVERTED_MOB_DEFAULT_DMG).add(ModAttributes.SUNDAMAGE, BalanceMobProps.mobProps.VAMPIRE_MOB_SUN_DAMAGE);
                        }

                        public static boolean checkSpawnRules(EntityType<? extends Animal> type, LevelAccessor level, EntitySpawnReason reason, BlockPos pos, RandomSource random) {
                            return level.getDifficulty() != Difficulty.PEACEFUL && %1$s.%3$s(type, level, reason, pos, random);
                        }

                    """.formatted(m.baseSimple(), m.attributeMethod(), m.spawnRulesFrom());

        String pkg = m.packageName().isEmpty() ? "" : "package " + m.packageName() + ";\n\n";
        return pkg + im + "\n" + """
                /**
                 * Generated by {@code de.teamlapen.vampirism.processor.ConvertedCreatureProcessor} for {@link %2$s}.
                 * Subclass it (see @ConvertedCreature#subclass) to add entity specific bits.
                 */
                public abstract class %1$s extends %2$s implements CurableConvertedCreature<%2$s, %1$s> {

                    private static final EntityDataAccessor<Boolean> CONVERTING = SynchedEntityData.defineId(%1$s.class, EntityDataSerializers.BOOLEAN);

                    private final Data<%2$s> data = new Data<>();

                    protected %1$s(EntityType<? extends %1$s> type, Level world) {
                        super(type, world);
                    }

                %3$s    @Override
                    public @NotNull EntityType<%2$s> getCuredEntityType() {
                        return EntityType.%4$s;
                    }

                    @Override
                    public @NotNull EntityDataAccessor<Boolean> getConvertingDataParam() {
                        return CONVERTING;
                    }

                    @Override
                    public Data<%2$s> data() {
                        return this.data;
                    }

                    @Override
                    public void handleEntityEventSuper(byte id) {
                        super.handleEntityEvent(id);
                    }

                    @Override
                    public InteractionResult mobInteractSuper(@NotNull Player player, @NotNull InteractionHand hand) {
                        return super.mobInteract(player, hand);
                    }

                    @Override
                    public boolean hurtSuper(ServerLevel level, DamageSource damageSource, float amount) {
                        return super.hurtServer(level, damageSource, amount);
                    }

                    @Override
                    public void addAdditionalSaveData(@NotNull ValueOutput output) {
                        super.addAdditionalSaveData(output);
                        this.addAdditionalSaveDataC(output);
                    }

                    @Override
                    public void aiStep() {
                        if (this.level() instanceof ServerLevel serverLevel) {
                            aiStepC(serverLevel);
                        }
                        super.aiStep();
                    }

                    @Override
                    public void die(@NotNull DamageSource cause) {
                        super.die(cause);
                        this.dieC(cause);
                    }

                    @Override
                    public @NotNull Component getTypeName() {
                        return this.getNameC(EntityType.%4$s::getDescription);
                    }

                    @Override
                    public boolean hurtServer(@NotNull ServerLevel level, @NotNull DamageSource source, float amount) {
                        return this.hurtC(level, source, amount);
                    }

                    @Override
                    public @NotNull InteractionResult mobInteract(@NotNull Player player, @NotNull InteractionHand hand) {
                        return mobInteractC(player, hand);
                    }

                    @Override
                    public void readAdditionalSaveData(@NotNull ValueInput input) {
                        super.readAdditionalSaveData(input);
                        this.readAdditionalSaveDataC(input);
                    }

                    @Override
                    protected void defineSynchedData(SynchedEntityData.Builder builder) {
                        super.defineSynchedData(builder);
                        this.registerConvertingData(builder);
                    }

                    @Override
                    protected void registerGoals() {
                        super.registerGoals();
                        this.registerGoalsC();
                    }

                    @Override
                    protected void tickDeath() {
                        super.tickDeath();
                        this.tickDeathC();
                    }

                    @Override
                    public void tick() {
                        super.tick();
                        this.tickC();
                    }
                }
                """.formatted(m.className(), m.baseSimple(), statics, m.entityType());
    }
}
