@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.teamlapen.vampirism;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;