tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.ALL
}

ext.registerJarFiles = { List<String> filePaths ->
    tasks.withType(Jar).configureEach {
        filePaths.each { path ->
            from(rootProject.file(path))
        }
    }
}

subprojects {
    apply plugin: 'eclipse'
    apply plugin: 'maven-publish'
    apply from: rootProject.file('gradle/idea.gradle')
    apply from: rootProject.file('gradle/license.gradle')

    afterEvaluate {
        def mavenUrl = System.getenv("MAVEN_URL")
        if (mavenUrl) {
            publishing {
                repositories {
                    maven {
                        url = mavenUrl
                        credentials {
                            username = System.getenv("MAVEN_USERNAME") ?: ""
                            password = System.getenv("MAVEN_PASSWORD") ?: ""
                        }
                    }
                }
            }
        }
    }
}