plugins {
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id "com.modrinth.minotaur" version "2.4.5"
    id 'de.undercouch.download' version '3.3.0'
    id 'idea'
    id 'eclipse'
    id "me.modmuss50.mod-publish-plugin" version "0.4.2"
    id 'net.neoforged.moddev' version '2.0.116'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.ALL
}

group = mod_group_id
version = mod_version

base {
    archivesName = mod_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

apply from: 'gradle/versioning.gradle'

sourceSets {
    extension {
        compileClasspath += configurations["compileClasspath"]
    }
    api {
        compileClasspath += configurations["compileClasspath"]
        compileClasspath += sourceSets.extension.output
    }
    //noinspection GroovyAssignabilityCheck
    main {

        java {
            //if you want to exclude a package do it here, but use the package as path (e.g. de/teamlapen/vampirism for de.teamlapen.vampirism)
            // if you want intellij to ignore the package, you need to add it in the settings (File -> Settings -> Build, Execution, Deployment -> Compiler -> Excludes)
            // exclude(<package>)
            if (!include_jei.toBoolean()) {
                exclude('de/teamlapen/vampirism/common/integration/jei')
            }
            if (!include_guideapi.toBoolean()) {
                exclude('de/teamlapen/vampirism/common/integration/guide')
            }
            if (!include_terrablender.toBoolean()) {
                exclude('de/teamlapen/vampirism/common/integration/terrablender')
            }
        }
        compileClasspath += sourceSets.api.output
        runtimeClasspath += sourceSets.api.output

        compileClasspath += sourceSets.extension.output
        runtimeClasspath += sourceSets.extension.output

        resources.srcDirs += 'src/generated/resources'
    }
    test {
        compileClasspath += sourceSets.api.output
        runtimeClasspath += sourceSets.api.output
        compileClasspath += sourceSets.extension.output
        runtimeClasspath += sourceSets.extension.output
    }
}

neoForge {
    version = project.neo_version

    interfaceInjectionData.from "src/main/resources/META-INF/interfaceinjection.json"

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        configureEach {
//            systemProperty 'forge.logging.markers', "SCAN,REGISTRIES,REGISTRYDUMP"

            logLevel = org.slf4j.event.Level.WARN //ERROR,WARN,INFO,DEBUG,TRACE

            jvmArgument '-XX:+AllowEnhancedClassRedefinition'
            jvmArgument '-XX:+IgnoreUnrecognizedVMOptions'

            systemProperty 'mixin.debug.export', 'true'
        }

        client {
            client()

            systemProperty 'vampirism_target', 'dev'
            systemProperty 'guideapi_target', 'dev'

            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'

            systemProperty 'vampirism_target', 'dev'

            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"

            systemProperty 'vampirism_target', 'dev'

            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()

            systemProperty 'vampirism_target', 'dev_data'

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(sourceSets.api)
            sourceSet(sourceSets.extension)
        }
    }
}

apply from: 'gradle/dependencies.gradle'

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

//apply from: 'gradle/forge.gradle'
//apply from: 'gradle/artifacts.gradle'
//apply from: 'gradle/deploy.gradle'
//apply from: 'gradle/crowdin.gradle'

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            mod_issue_tracker      : mod_issue_tracker,
            mod_url                : mod_url,
            mod_update_url         : mod_update_url,
            jei_version            : jei_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

apply from: 'gradle/deploy.gradle'

idea {
    module {
        for (String excludeDirName in ["run", "out", "logs", "runs"]) {
            File excludeDir = new File(projectDir, excludeDirName)
            excludeDirs.add(excludeDir)
        }
        downloadSources = true
        downloadJavadoc = true
    }
}