project_id: "113663"
base_path: .

preserve_hierarchy: true
pull_request_labels:
  - Translations
files:
  - source: /projects/faction/src/main/resources/assets/factionapi/lang/en_us.json
    translation: /projects/faction/src/main/resources/assets/factionapi/lang/%locale_with_underscore%.%file_extension%
    dest: /factionapi.%file_extension%
  - source: /projects/vampirism/src/main/resources/assets/vampirism/lang/en_us.json
    translation: /projects/vampirism/src/main/resources/assets/vampirism/lang/%locale_with_underscore%.%file_extension%
    dest: /vampirism.%file_extension%
  - source: /projects/vampirism/src/main/resources/assets/vampirismguide/lang/en_us.json
    translation: /projects/vampirism/src/main/resources/assets/vampirismguide/lang/%locale_with_underscore%.%file_extension%
    dest: /vampirismguide.%file_extension%