# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# java
java_version=25

# neoforge
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neoforge_version=26.1.2.99

# factions
factions_mod_version=1.0.0
factions_mod_id=factionapi
factions_mod_name=FactionApi
factions_license=LGPL-3.0
factions_group_id=de.teamlapen.faction
factions_authors=maxanier, cheaterpaul, gridexpert
factions_description=A factions mod for Minecraft
factions_issue_tracker=https://github.com/TeamLapen/Vampirism/issues
factions_update_url=https://api.modrinth.com/updates/factionapi/forge_updates.json?neoforge=only

# vampirism
vampirism_mod_version=2.0.0
vampirism_mod_id=vampirism
vampirism_mod_name=Vampirism
vampirism_mod_license=LGPL-3.0
vampirism_group_id=de.teamlapen.vampirism
vampirism_authors=maxanier, cheaterpaul, gridexpert
vampirism_description=Allows you to become a vampire
vampirism_url=https://vampirism.dev
vampirism_issue_tracker=https://github.com/TeamLapen/Vampirism/issues
vampirism_update_url=https://api.modrinth.com/updates/vampirism/forge_updates.json?neoforge=only
vampirism_factions_source_dependency=true
vampirism_factions_version=26.1.2-1.0.0-dev.1

# integrations
# jei
include_jei=true
jei_mc_version=26.1.2
jei_version=29.34.0.90

# guide-api
include_guideapi=true
guideapi_mc_version=26.1.2
guideapi_version=3.0.0-beta.1

# terrablender
include_terrablender=true
terrablender_version=26.1.2-26.1.2.0.1

# runtime helper
# jade
include_jade=false
jade_version=5729884
include_jer=false
jer_version=tBAdXL1H

#appleskin (factionapi)
include_appleskin=true
appleskin_version=mc26.1-3.0.9
