# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# neoforge
minecraft_version=1.21.10
minecraft_version_range=[1.21.10,1.22)
neo_version=21.10.49-beta
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

# mod
mod_id=vampirism
mod_name=Vampirism
mod_license=LGPL-3.0
main_version=1
major_version=11
minor_version=0
mod_group_id=de.teamlapen.vampirism
mod_authors=maxanier, cheaterpaul
mod_description=Allows you to become a vampire
mod_url=https://vampirism.dev
mod_issue_tracker=https://github.com/TeamLapen/Vampirism/issues
mod_update_url=https://api.modrinth.com/updates/vampirism/forge_updates.json

modrinth_id=jVZ0F1wn
curseforge_id=233029
curseforge_slug=vampirism-become-a-vampire


# properties will be overridden in gradle/versioning.gradle
mod_version="Test"
type="test"
classification="test"

#jei setting
include_jei=true
jei_mc_version=1.21.10
jei_version=26.1.0.16

#guideapi setting
include_guideapi=false
guideapi_version=1.21.1-2.3.0

#terrablender setting
include_terrablender=true
terrablender_version=1.21.10-21.10.0.0

#jade
include_jade=false
jade_version=5729884
