# gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# java
java_version=21

# neoforge
minecraft_version=1.21.10
minecraft_version_range=[1.21.10,1.22)
neoforge_version=21.10.63
parchment_minecraft_version=1.21.10
parchment_mappings_version=2025.10.12

# factions
factions_mod_id=factions
factions_mod_name=Factions
factions_license=LGPL-3.0
factions_version=0.1.0
factions_group_id=de.teamlapen.factions
factions_authors=maxanier, cheaterpaul
factions_description=A factions mod for Minecraft
factions_issue_tracker=https://github.com/TeamLapen/Factions/issues

# vampirism
vampirism_mod_id=vampirism
vampirism_mod_name=Vampirism
vampirism_mod_license=LGPL-3.0
vampirism_version=2.0.0
vampirism_group_id=de.teamlapen.vampirism
vampirism_authors=maxanier, cheaterpaul
vampirism_description=Allows you to become a vampire
vampirism_url=https://vampirism.dev
vampirism_issue_tracker=https://github.com/TeamLapen/Vampirism/issues
vampirism_update_url=https://api.modrinth.com/updates/vampirism/forge_updates.json

vampirism_modrinth_id=jVZ0F1wn
vampirism_curseforge_id=233029
vampirism_curseforge_slug=vampirism-become-a-vampire

#jei setting
include_jei=true
jei_mc_version=1.21.10
jei_version=26.1.0.16

#guideapi setting
include_guideapi=false
guideapi_version=1.21.1-2.3.0

#terrablender setting
include_terrablender=true
terrablender_version=1.21.10-21.10.0.0

#jade
include_jade=false
jade_version=5729884
