pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name= "Vampirism"

// Enable multi-project build: separate mods/modules

include(
        ':factions-api',
        ':factions',
        ':vampirism-api',
        ':vampirism'
)

project(':factions-api').projectDir = file("projects/factions-api")
project(':factions').projectDir = file("projects/factions")
project(':vampirism-api').projectDir = file("projects/vampirism-api")
project(':vampirism').projectDir = file("projects/vampirism")