@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package de.teamlapen.vampirism.effects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;