modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mixins]]
config = "vampirism.mixins.json"

[[mods]]
modId = "${mod_id}"
namespace = "vampirism"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
credits = '''\n
     - 1LiterZinalco (triage/textures/models)
     - TheRebelT (textures)
     - TinkerHatWill (textures)
     - Alis (textures)
     - dimensionpainter (textures)
     - S_olace (textures)
     - Mistadon (code/models)
     - wildbill22 (code)
     - LRA_10 (models/textures)
     - Oreo365 (models)
     - Slippingchip400 (models)
     - Йода (textures)
     - XxKidDowdallxX (texture)
     - F_Spade (textures)
     - Matheo (lore)
     - cournualllama2 (lore)
     - special_krab (lore)
     - Random (textures/models)
     - Shumnik (textures/models)
     - BugraaK (textures/models)
     - MrVityaTrash (textures)
     - FrostedOver (textures)
     - Grid (textures)
     - T_Corvus (textures)
     - Zeyke (textures)
     - freesound.org (sounds)
     - freeSFX.co.uk (sounds)'''
description = '''${mod_description}'''
displayURL = "${mod_url}"
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/vampirism/forge_updates.json"
enumExtensions = "META-INF/enumextensions.json"
[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "teamlapenlib"
type = "required"
versionRange = "[${mod_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "guideapi-vp"
type = "optional"
versionRange = "[${guideapi_version},)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"
[[mods]]
modId = "teamlapenlib"
namespace = "teamlapenlib"
version = "${mod_version}"
displayName = "Teamlapen Library"
authors = "${mod_authors}"
description = "Required by Vampirism"
displayURL = "${mod_url}"
[[dependencies.teamlapen-lib]]
modId = "neoforge"
type = "required"
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"