repositories {
    maven {
        // location of a maven mirror for JEI files
        name = "ModMaven"
        url = "https://modmaven.dev/"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven {
        name = "Maxanier"
        url = "https://maven.maxanier.de/releases"
        content {
            includeGroupAndSubgroups "de.teamlapen"
            includeGroupAndSubgroups "de.maxanier"
        }
    }
    maven {
        url "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        name = "MinecraftForge"
        url "https://maven.minecraftforge.net/"
        content {
            includeGroup "com.github.glitchfiend"
        }
    }
    maven {
        name = "RyanLiptak"
        url = "https://maven.ryanliptak.com/"
        content {
            includeGroupAndSubgroups "squeek"
        }
    }
}

dependencies {
    if (include_jei.toBoolean()) {
        compileOnly "mezz.jei:jei-${jei_mc_version}-common-api:${project.jei_version}"
        compileOnly "mezz.jei:jei-${jei_mc_version}-neoforge-api:${project.jei_version}"
        runtimeOnly "mezz.jei:jei-${jei_mc_version}-neoforge:${project.jei_version}"
    }

    if (include_guideapi.toBoolean()) {
        compileOnly "de.maxanier.guideapi:Guide-API-VP:${guideapi_mc_version}-${project.guideapi_version}"
        runtimeOnly "de.maxanier.guideapi:Guide-API-VP:${guideapi_mc_version}-${project.guideapi_version}"
    }

    if (include_terrablender.toBoolean()) {
        compileOnly "com.github.glitchfiend:TerraBlender-neoforge:${project.terrablender_version}"
        runtimeOnly "com.github.glitchfiend:TerraBlender-neoforge:${project.terrablender_version}"
    }

    if (include_jade.toBoolean()) {
        runtimeOnly "curse.maven:jade-324717:" + project.jade_version
    }
}