@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package de.teamlapen.vampirism.common.blockentity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;