license = "${mod_license}"
issueTrackerURL = "${mod_issue_tracker}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "${mod_update_url}"
displayURL = "${mod_url}"
logoFile = "logo.png"
credits = '''\n
     - 1LiterZinalco (triage/textures/models)
     - TheRebelT (textures)
     - TinkerHatWill (textures)
     - Alis (textures)
     - dimensionpainter (textures)
     - S_olace (textures)
     - Mistadon (code/models)
     - wildbill22 (code)
     - LRA_10 (models/textures)
     - Oreo365 (models)
     - Slippingchip400 (models)
     - Йода (textures)
     - XxKidDowdallxX (texture)
     - F_Spade (textures)
     - Matheo (lore)
     - cournualllama2 (lore)
     - special_krab (lore)
     - Random (textures/models)
     - Shumnik (textures/models)
     - BugraaK (textures/models)
     - MrVityaTrash (textures)
     - FrostedOver (textures)
     - T_Corvus (textures)
     - Zeyke (textures)
     - zozozrob (textures/models)
     - freesound.org (sounds)
     - freeSFX.co.uk (sounds)'''

authors = "${mod_authors}"
description = '''${mod_description}'''
enumExtensions = "META-INF/enumextensions.json"

[[mixins]]
config = "${mod_id}.mixins.json"

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId="${factions_mod_id}"
type = "required"
versionRange = "[${vampirism_factions_version},)"
ordering="AFTER"
side="BOTH"

[[dependencies.${ mod_id }]]
modId = "jei"
type = "optional"
versionRange = "[${jei_version},)"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "guideapi_vp"
type = "optional"
versionRange = "[${guideapi_version},)"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "terrablender"
type = "optional"
versionRange = "[${terrablender_version},)"
side = "BOTH"
