package de.teamlapen.vampirism.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

/**
 * 
 * @author Moritz
 *
 */
public class ModelBloodAltarTier2 extends ModelBase {
	// fields
	ModelRenderer PillarFL;
	ModelRenderer PillarFR;
	ModelRenderer PillarBL;
	ModelRenderer PillarBR;
	ModelRenderer Base;
	ModelRenderer[][] sphere;
	ModelRenderer[][] liquid;

	public ModelBloodAltarTier2() {
		textureWidth = 64;
		textureHeight = 128;
		
		sphere = new ModelRenderer[16][0];
		liquid = new ModelRenderer[16][0];

		PillarFL = new ModelRenderer(this, 0, 7);
		PillarFL.addBox(0F, 0F, 0F, 1, 4, 1);
		PillarFL.setRotationPoint(-8F, 18F, -8F);
		PillarFL.setTextureSize(64, 32);
		PillarFL.mirror = true;
		setRotation(PillarFL, 0F, 0F, 0F);
		PillarFR = new ModelRenderer(this, 0, 7);
		PillarFR.addBox(0F, 0F, 0F, 1, 4, 1);
		PillarFR.setRotationPoint(7F, 18F, -8F);
		PillarFR.setTextureSize(64, 32);
		PillarFR.mirror = true;
		setRotation(PillarFR, 0F, 0F, 0F);
		PillarBL = new ModelRenderer(this, 0, 7);
		PillarBL.addBox(0F, 0F, 0F, 1, 4, 1);
		PillarBL.setRotationPoint(-8F, 18F, 7F);
		PillarBL.setTextureSize(64, 32);
		PillarBL.mirror = true;
		setRotation(PillarBL, 0F, 0F, 0F);
		PillarBR = new ModelRenderer(this, 0, 7);
		PillarBR.addBox(0F, 0F, 0F, 1, 4, 1);
		PillarBR.setRotationPoint(7F, 18F, 7F);
		PillarBR.setTextureSize(64, 32);
		PillarBR.mirror = true;
		setRotation(PillarBR, 0F, 0F, 0F);
	      Base = new ModelRenderer(this, 0, 110);
	      Base.addBox(-8F, 23F, -8F, 16, 2, 16);
	      Base.setRotationPoint(0F, -1F, 0F);
	      Base.setTextureSize(64, 128);
	      Base.mirror = true;
	      setRotation(Base, 0F, 0F, 0F);
	      addRing(0,0,0,0);
	      addRing(1,1,0,0);
	      addRing(2,2,0,3);
	      addRing(3,3,0,6);
	      addRing(4,4,0,10);
	      addRing(5,5,0,17);
	      addRing(6,6,0,28);
	      addRing(7,7,0,39);
	      addRing(7,8,-1,50);
	      addRing(6,9,-3,61);
	      addRing(5,10,-5,72);
	      addRing(4,11,-7,83);
	      addRing(3,12,-9,90);
	      addRing(2,13,-11,94);
	      addRing(1,14,-13,98);
	      addRing(0,15,-15,0);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		PillarFL.render(f5);
		PillarFR.render(f5);
		PillarBL.render(f5);
		PillarBR.render(f5);
		Base.render(f5);
		for(ModelRenderer[] i : sphere)
			if(i!=null)
				for(ModelRenderer j : i)
					if(j!=null)
						j.render(f5);
		for(ModelRenderer[] i : liquid)
			if(i!=null)
				for(ModelRenderer j : i)
					if(j!=null)
						j.render(f5);
	}

	private void addRing(int number, int arrayNumber, int offset, int texOffset) {
		switch (number){
			case 0:
				sphere[arrayNumber] = new ModelRenderer[5];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-1F, 23F + offset, -3F, 2, 1, 6);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-2F, 23F + offset, -2F, 1, 1, 4);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-3F, 23F + offset, -1F, 1, 1, 2);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(1F, 23F + offset, -2F, 1, 1, 4);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(2F, 23F + offset, -1F, 1, 1, 2);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				break;
			case 1:
				sphere[arrayNumber] = new ModelRenderer[12];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-1F, 22F + offset, -5F, 2, 1, 2);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-3F, 22F + offset, -4F, 2, 1, 2);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-4F, 22F + offset, -3F, 2, 1, 2);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-5F, 22F + offset, -1F, 2, 1, 2);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-4F, 22F + offset, 1F, 2, 1, 2);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-3F, 22F + offset, 2F, 2, 1, 2);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-1F, 22F + offset, 3F, 2, 1, 2);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(1F, 22F + offset, 2F, 2, 1, 2);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(2F, 22F + offset, 1F, 2, 1, 2);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(3F, 22F + offset, -1F, 2, 1, 2);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(2F, 22F + offset, -3F, 2, 1, 2);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(1F, 22F + offset, -4F, 2, 1, 2);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[5];
				liquid[arrayNumber][0] = new ModelRenderer(this, 48, texOffset);
				liquid[arrayNumber][0].addBox(-3F, 22F + offset, -1F, 6, 1, 2);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 54, texOffset);
				liquid[arrayNumber][1].addBox(-2F, 22F + offset, -2F, 4, 1, 1);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 51, texOffset);
				liquid[arrayNumber][2].addBox(-2F, 22F + offset, 1F, 4, 1, 1);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 48, texOffset);
				liquid[arrayNumber][3].addBox(-1F, 22F + offset, 2F, 2, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 53, texOffset);
				liquid[arrayNumber][4].addBox(-1F, 22F + offset, -3F, 2, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				break;
			case 2:
				sphere[arrayNumber] = new ModelRenderer[16];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-2F, 21F + offset, -6F, 4, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-4F, 21F + offset, -5F, 3, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-5F, 21F + offset, -4F, 2, 1, 1);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-5F, 21F + offset, -3F, 1, 1, 2);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-6F, 21F + offset, -2F, 1, 1, 4);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-5F, 21F + offset, 1F, 1, 1, 2);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-5F, 21F + offset, 3F, 2, 1, 1);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(-4F, 21F + offset, 4F, 3, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(-2F, 21F + offset, 5F, 4, 1, 1);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(1F, 21F + offset, 4F, 3, 1, 1);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(3F, 21F + offset, 3F, 2, 1, 1);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(4F, 21F + offset, 1F, 1, 1, 2);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				sphere[arrayNumber][12] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][12].addBox(5F, 21F + offset, -2F, 1, 1, 4);
				sphere[arrayNumber][12].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][12].setTextureSize(64, 32);
				sphere[arrayNumber][12].mirror = true;
				setRotation(sphere[arrayNumber][12], 0F, 0F, 0F);
				sphere[arrayNumber][13] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][13].addBox(4F, 21F + offset, -3F, 1, 1, 2);
				sphere[arrayNumber][13].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][13].setTextureSize(64, 32);
				sphere[arrayNumber][13].mirror = true;
				setRotation(sphere[arrayNumber][13], 0F, 0F, 0F);
				sphere[arrayNumber][14] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][14].addBox(3F, 21F + offset, -4F, 2, 1, 1);
				sphere[arrayNumber][14].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][14].setTextureSize(64, 32);
				sphere[arrayNumber][14].mirror = true;
				setRotation(sphere[arrayNumber][14], 0F, 0F, 0F);
				sphere[arrayNumber][15] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][15].addBox(1F, 21F + offset, -5F, 3, 1, 1);
				sphere[arrayNumber][15].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][15].setTextureSize(64, 32);
				sphere[arrayNumber][15].mirror = true;
				setRotation(sphere[arrayNumber][15], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[8];
				liquid[arrayNumber][0] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][0].addBox(-5F, 21F + offset, -1F, 10, 1, 2);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][1].addBox(-4F, 21F + offset, 1F, 8, 1, 2);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][2].addBox(-4F, 21F + offset, -3F, 8, 1, 2);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 42, texOffset);
				liquid[arrayNumber][3].addBox(-3F, 21F + offset, -4F, 6, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][4].addBox(-3F, 21F + offset, 3F, 6, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				liquid[arrayNumber][5] = new ModelRenderer(this, 50, texOffset);
				liquid[arrayNumber][5].addBox(-1F, 21F + offset, 4F, 2, 1, 1);
				liquid[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][5].setTextureSize(64, 128);
				liquid[arrayNumber][5].mirror = true;
				setRotation(liquid[arrayNumber][5], 0F, 0F, 0F);
				liquid[arrayNumber][6] = new ModelRenderer(this, 48, texOffset);
				liquid[arrayNumber][6].addBox(-1F, 21F + offset, -5F, 2, 1, 1);
				liquid[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][6].setTextureSize(64, 128);
				liquid[arrayNumber][6].mirror = true;
				setRotation(liquid[arrayNumber][6], 0F, 0F, 0F);
				break;
			case 3:
				sphere[arrayNumber] = new ModelRenderer[16];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-1F, 20F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-4F, 20F + offset, -6F, 3, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-5F, 20F + offset, -5F, 1, 1, 1);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-6F, 20F + offset, -4F, 1, 1, 3);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-7F, 20F + offset, -1F, 1, 1, 2);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-6F, 20F + offset, 1F, 1, 1, 3);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-5F, 20F + offset, 4F, 1, 1, 1);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(-1F, 20F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(-4F, 20F + offset, 5F, 3, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(1F, 20F + offset, 5F, 3, 1, 1);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(4F, 20F + offset, 4F, 1, 1, 1);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(5F, 20F + offset, 1F, 1, 1, 3);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				sphere[arrayNumber][13] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][13].addBox(5F, 20F + offset, -4F, 1, 1, 3);
				sphere[arrayNumber][13].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][13].setTextureSize(64, 32);
				sphere[arrayNumber][13].mirror = true;
				setRotation(sphere[arrayNumber][13], 0F, 0F, 0F);
				sphere[arrayNumber][12] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][12].addBox(6F, 20F + offset, -1F, 1, 1, 2);
				sphere[arrayNumber][12].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][12].setTextureSize(64, 32);
				sphere[arrayNumber][12].mirror = true;
				setRotation(sphere[arrayNumber][12], 0F, 0F, 0F);
				sphere[arrayNumber][14] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][14].addBox(4F, 20F + offset, -5F, 1, 1, 1);
				sphere[arrayNumber][14].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][14].setTextureSize(64, 32);
				sphere[arrayNumber][14].mirror = true;
				setRotation(sphere[arrayNumber][14], 0F, 0F, 0F);
				sphere[arrayNumber][15] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][15].addBox(1F, 20F + offset, -6F, 3, 1, 1);
				sphere[arrayNumber][15].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][15].setTextureSize(64, 32);
				sphere[arrayNumber][15].mirror = true;
				setRotation(sphere[arrayNumber][15], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[8];
				liquid[arrayNumber][0] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][0].addBox(-6F, 20F + offset, -1F, 12, 1, 2);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][1].addBox(-5F, 20F + offset, 1F, 10, 1, 3);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 38, texOffset);
				liquid[arrayNumber][2].addBox(-5F, 20F + offset, -4F, 10, 1, 3);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 44, texOffset);
				liquid[arrayNumber][3].addBox(-4F, 20F + offset, -5F, 8, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][4].addBox(-4F, 20F + offset, 4F, 8, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				liquid[arrayNumber][5] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][5].addBox(-1F, 20F + offset, 5F, 2, 1, 1);
				liquid[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][5].setTextureSize(64, 128);
				liquid[arrayNumber][5].mirror = true;
				setRotation(liquid[arrayNumber][5], 0F, 0F, 0F);
				liquid[arrayNumber][6] = new ModelRenderer(this, 52, texOffset);
				liquid[arrayNumber][6].addBox(-1F, 20F + offset, -6F, 2, 1, 1);
				liquid[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][6].setTextureSize(64, 128);
				liquid[arrayNumber][6].mirror = true;
				setRotation(liquid[arrayNumber][6], 0F, 0F, 0F);
				break;
			case 4: 
				sphere[arrayNumber] = new ModelRenderer[12];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-3F, 19F + offset, -7F, 6, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-5F, 19F + offset, -6F, 2, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-6F, 19F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-7F, 19F + offset, -3F, 1, 1, 6);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-6F, 19F + offset, 3F, 1, 1, 2);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-5F, 19F + offset, 5F, 2, 1, 1);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(3F, 19F + offset, 5F, 2, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(5F, 19F + offset, 3F, 1, 1, 2);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(6F, 19F + offset, -3F, 1, 1, 6);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(5F, 19F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-3F, 19F + offset, 6F, 6, 1, 1);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(3F, 19F + offset, -6F, 2, 1, 1);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[6];
				liquid[arrayNumber][0] = new ModelRenderer(this, 34, texOffset);
				liquid[arrayNumber][0].addBox(-6F, 19F + offset, -3F, 12, 1, 6);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 38, texOffset);
				liquid[arrayNumber][1].addBox(-5F, 19F + offset, -5F, 10, 1, 2);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][2].addBox(-5F, 19F + offset, 3F, 10, 1, 2);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 44, texOffset);
				liquid[arrayNumber][3].addBox(-3F, 19F + offset, 5F, 6, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][4].addBox(-3F, 19F + offset, -6F, 6, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				break;
			case 5:
				sphere[arrayNumber] = new ModelRenderer[20];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-1F, 18F + offset, -8F, 2, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-4F, 18F + offset, -7F, 3, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-5F, 18F + offset, -6F, 1, 1, 1);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-6F, 18F + offset, -5F, 1, 1, 1);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-7F, 18F + offset, -4F, 1, 1, 3);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-8F, 18F + offset, -1F, 1, 1, 2);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-7F, 18F + offset, 1F, 1, 1, 3);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(-6F, 18F + offset, 4F, 1, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(-5F, 18F + offset, 5F, 1, 1, 1);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(-1F, 18F + offset, 7F, 2, 1, 1);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(-4F, 18F + offset, 6F, 3, 1, 1);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][12] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][12].addBox(4F, 18F + offset, 5F, 1, 1, 1);
				sphere[arrayNumber][12].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][12].setTextureSize(64, 32);
				sphere[arrayNumber][12].mirror = true;
				setRotation(sphere[arrayNumber][12], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(1F, 18F + offset, 6F, 3, 1, 1);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				sphere[arrayNumber][13] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][13].addBox(5F, 18F + offset, 4F, 1, 1, 1);
				sphere[arrayNumber][13].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][13].setTextureSize(64, 32);
				sphere[arrayNumber][13].mirror = true;
				setRotation(sphere[arrayNumber][13], 0F, 0F, 0F);
				sphere[arrayNumber][14] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][14].addBox(6F, 18F + offset, 1F, 1, 1, 3);
				sphere[arrayNumber][14].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][14].setTextureSize(64, 32);
				sphere[arrayNumber][14].mirror = true;
				setRotation(sphere[arrayNumber][14], 0F, 0F, 0F);
				sphere[arrayNumber][15] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][15].addBox(7F, 18F + offset, -1F, 1, 1, 2);
				sphere[arrayNumber][15].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][15].setTextureSize(64, 32);
				sphere[arrayNumber][15].mirror = true;
				setRotation(sphere[arrayNumber][15], 0F, 0F, 0F);
				sphere[arrayNumber][17] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][17].addBox(5F, 18F + offset, -5F, 1, 1, 1);
				sphere[arrayNumber][17].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][17].setTextureSize(64, 32);
				sphere[arrayNumber][17].mirror = true;
				setRotation(sphere[arrayNumber][17], 0F, 0F, 0F);
				sphere[arrayNumber][18] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][18].addBox(4F, 18F + offset, -6F, 1, 1, 1);
				sphere[arrayNumber][18].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][18].setTextureSize(64, 32);
				sphere[arrayNumber][18].mirror = true;
				setRotation(sphere[arrayNumber][18], 0F, 0F, 0F);
				sphere[arrayNumber][16] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][16].addBox(6F, 18F + offset, -4F, 1, 1, 3);
				sphere[arrayNumber][16].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][16].setTextureSize(64, 32);
				sphere[arrayNumber][16].mirror = true;
				setRotation(sphere[arrayNumber][16], 0F, 0F, 0F);
				sphere[arrayNumber][19] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][19].addBox(1F, 18F + offset, -7F, 3, 1, 1);
				sphere[arrayNumber][19].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][19].setTextureSize(64, 32);
				sphere[arrayNumber][19].mirror = true;
				setRotation(sphere[arrayNumber][19], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[10];
				liquid[arrayNumber][0] = new ModelRenderer(this, 24, texOffset);
				liquid[arrayNumber][0].addBox(-5F, 18F + offset, -5F, 10, 1, 10);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][1].addBox(-7F, 18F + offset, -1F, 1, 1, 2);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 50, texOffset);
				liquid[arrayNumber][2].addBox(6F, 18F + offset, -1F, 1, 1, 2);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][3].addBox(-1F, 18F + offset, -7F, 2, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][4].addBox(-1F, 18F + offset, 6F, 2, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				liquid[arrayNumber][5] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][5].addBox(-4F, 18F + offset, 5F, 8, 1, 1);
				liquid[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][5].setTextureSize(64, 128);
				liquid[arrayNumber][5].mirror = true;
				setRotation(liquid[arrayNumber][5], 0F, 0F, 0F);
				liquid[arrayNumber][6] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][6].addBox(-4F, 18F + offset, -6F, 8, 1, 1);
				liquid[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][6].setTextureSize(64, 128);
				liquid[arrayNumber][6].mirror = true;
				setRotation(liquid[arrayNumber][6], 0F, 0F, 0F);
				liquid[arrayNumber][7] = new ModelRenderer(this, 35, texOffset);
				liquid[arrayNumber][7].addBox(-6F, 18F + offset, -4F, 1, 1, 8);
				liquid[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][7].setTextureSize(64, 128);
				liquid[arrayNumber][7].mirror = true;
				setRotation(liquid[arrayNumber][7], 0F, 0F, 0F);
				liquid[arrayNumber][8] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][8].addBox(5F, 18F + offset, -4F, 1, 1, 8);
				liquid[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][8].setTextureSize(64, 128);
				liquid[arrayNumber][8].mirror = true;
				setRotation(liquid[arrayNumber][8], 0F, 0F, 0F);
				break;
			case 6:
				sphere[arrayNumber] = new ModelRenderer[20];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-2F, 17F + offset, -8F, 4, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-4F, 17F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-6F, 17F + offset, -6F, 2, 1, 1);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-6F, 17F + offset, -5F, 1, 1, 1);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-6F, 17F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][4].setRotationPoint(-1F, 0F, 1F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-7F, 17F + offset, -3F, 1, 1, 4);
				sphere[arrayNumber][5].setRotationPoint(-1F, 0F, 1F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-6F, 17F + offset, 1F, 1, 1, 2);
				sphere[arrayNumber][6].setRotationPoint(-1F, 0F, 1F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(-6F, 17F + offset, 4F, 1, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(-6F, 17F + offset, 5F, 2, 1, 1);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(-4F, 17F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(-2F, 17F + offset, 7F, 4, 1, 1);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(2F, 17F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				sphere[arrayNumber][12] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][12].addBox(4F, 17F + offset, 5F, 2, 1, 1);
				sphere[arrayNumber][12].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][12].setTextureSize(64, 32);
				sphere[arrayNumber][12].mirror = true;
				setRotation(sphere[arrayNumber][12], 0F, 0F, 0F);
				sphere[arrayNumber][13] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][13].addBox(5F, 17F + offset, 4F, 1, 1, 1);
				sphere[arrayNumber][13].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][13].setTextureSize(64, 32);
				sphere[arrayNumber][13].mirror = true;
				setRotation(sphere[arrayNumber][13], 0F, 0F, 0F);
				sphere[arrayNumber][14] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][14].addBox(7F, 17F + offset, 1F, 1, 1, 2);
				sphere[arrayNumber][14].setRotationPoint(-1F, 0F, 1F);
				sphere[arrayNumber][14].setTextureSize(64, 32);
				sphere[arrayNumber][14].mirror = true;
				setRotation(sphere[arrayNumber][14], 0F, 0F, 0F);
				sphere[arrayNumber][15] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][15].addBox(8F, 17F + offset, -3F, 1, 1, 4);
				sphere[arrayNumber][15].setRotationPoint(-1F, 0F, 1F);
				sphere[arrayNumber][15].setTextureSize(64, 32);
				sphere[arrayNumber][15].mirror = true;
				setRotation(sphere[arrayNumber][15], 0F, 0F, 0F);
				sphere[arrayNumber][16] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][16].addBox(7F, 17F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][16].setRotationPoint(-1F, 0F, 1F);
				sphere[arrayNumber][16].setTextureSize(64, 32);
				sphere[arrayNumber][16].mirror = true;
				setRotation(sphere[arrayNumber][16], 0F, 0F, 0F);
				sphere[arrayNumber][17] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][17].addBox(5F, 17F + offset, -5F, 1, 1, 1);
				sphere[arrayNumber][17].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][17].setTextureSize(64, 32);
				sphere[arrayNumber][17].mirror = true;
				setRotation(sphere[arrayNumber][17], 0F, 0F, 0F);
				sphere[arrayNumber][18] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][18].addBox(4F, 17F + offset, -6F, 2, 1, 1);
				sphere[arrayNumber][18].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][18].setTextureSize(64, 32);
				sphere[arrayNumber][18].mirror = true;
				setRotation(sphere[arrayNumber][18], 0F, 0F, 0F);
				sphere[arrayNumber][19] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][19].addBox(2F, 17F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][19].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][19].setTextureSize(64, 32);
				sphere[arrayNumber][19].mirror = true;
				setRotation(sphere[arrayNumber][19], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[10];
				liquid[arrayNumber][0] = new ModelRenderer(this, 24, texOffset);
				liquid[arrayNumber][0].addBox(-5F, 17F + offset, -5F, 10, 1, 10);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 43, texOffset);
				liquid[arrayNumber][1].addBox(-7F, 17F + offset, -2F, 1, 1, 4);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][2].addBox(6F, 17F + offset, -2F, 1, 1, 4);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][3].addBox(-2F, 17F + offset, -7F, 4, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][4].addBox(-2F, 17F + offset, 6F, 4, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				liquid[arrayNumber][5] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][5].addBox(-4F, 17F + offset, 5F, 8, 1, 1);
				liquid[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][5].setTextureSize(64, 128);
				liquid[arrayNumber][5].mirror = true;
				setRotation(liquid[arrayNumber][5], 0F, 0F, 0F);
				liquid[arrayNumber][6] = new ModelRenderer(this, 41, texOffset);
				liquid[arrayNumber][6].addBox(-4F, 17F + offset, -6F, 8, 1, 1);
				liquid[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][6].setTextureSize(64, 128);
				liquid[arrayNumber][6].mirror = true;
				setRotation(liquid[arrayNumber][6], 0F, 0F, 0F);
				liquid[arrayNumber][7] = new ModelRenderer(this, 45, texOffset);
				liquid[arrayNumber][7].addBox(-6F, 17F + offset, -4F, 1, 1, 8);
				liquid[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][7].setTextureSize(64, 128);
				liquid[arrayNumber][7].mirror = true;
				setRotation(liquid[arrayNumber][7], 0F, 0F, 0F);
				liquid[arrayNumber][8] = new ModelRenderer(this, 43, texOffset);
				liquid[arrayNumber][8].addBox(5F, 17F + offset, -4F, 1, 1, 8);
				liquid[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][8].setTextureSize(64, 128);
				liquid[arrayNumber][8].mirror = true;
				setRotation(liquid[arrayNumber][8], 0F, 0F, 0F);
				break;
			case 7:
				sphere[arrayNumber] = new ModelRenderer[16];
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-3F, 16F + offset, -8F, 6, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-5F, 16F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-6F, 16F + offset, -6F, 1, 1, 1);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-7F, 16F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-8F, 16F + offset, -3F, 1, 1, 6);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-7F, 16F + offset, 3F, 1, 1, 2);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-6F, 16F + offset, 5F, 1, 1, 1);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(-5F, 16F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(-3F, 16F + offset, 7F, 6, 1, 1);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(3F, 16F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(5F, 16F + offset, 5F, 1, 1, 1);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(6F, 16F + offset, 3F, 1, 1, 2);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				sphere[arrayNumber][12] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][12].addBox(7F, 16F + offset, -3F, 1, 1, 6);
				sphere[arrayNumber][12].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][12].setTextureSize(64, 32);
				sphere[arrayNumber][12].mirror = true;
				setRotation(sphere[arrayNumber][12], 0F, 0F, 0F);
				sphere[arrayNumber][13] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][13].addBox(6F, 16F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][13].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][13].setTextureSize(64, 32);
				sphere[arrayNumber][13].mirror = true;
				setRotation(sphere[arrayNumber][13], 0F, 0F, 0F);
				sphere[arrayNumber][14] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][14].addBox(5F, 16F + offset, -6F, 1, 1, 1);
				sphere[arrayNumber][14].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][14].setTextureSize(64, 32);
				sphere[arrayNumber][14].mirror = true;
				setRotation(sphere[arrayNumber][14], 0F, 0F, 0F);
				sphere[arrayNumber][15] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][15].addBox(3F, 16F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][15].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][15].setTextureSize(64, 32);
				sphere[arrayNumber][15].mirror = true;
				setRotation(sphere[arrayNumber][15], 0F, 0F, 0F);
				sphere[arrayNumber][0] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][0].addBox(-3F, 15F + offset, -8F, 6, 1, 1);
				sphere[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][0].setTextureSize(64, 32);
				sphere[arrayNumber][0].mirror = true;
				setRotation(sphere[arrayNumber][0], 0F, 0F, 0F);
				sphere[arrayNumber][1] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][1].addBox(-5F, 15F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][1].setTextureSize(64, 32);
				sphere[arrayNumber][1].mirror = true;
				setRotation(sphere[arrayNumber][1], 0F, 0F, 0F);
				sphere[arrayNumber][2] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][2].addBox(-6F, 15F + offset, -6F, 1, 1, 1);
				sphere[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][2].setTextureSize(64, 32);
				sphere[arrayNumber][2].mirror = true;
				setRotation(sphere[arrayNumber][2], 0F, 0F, 0F);
				sphere[arrayNumber][3] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][3].addBox(-7F, 15F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][3].setTextureSize(64, 32);
				sphere[arrayNumber][3].mirror = true;
				setRotation(sphere[arrayNumber][3], 0F, 0F, 0F);
				sphere[arrayNumber][4] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][4].addBox(-8F, 15F + offset, -3F, 1, 1, 6);
				sphere[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][4].setTextureSize(64, 32);
				sphere[arrayNumber][4].mirror = true;
				setRotation(sphere[arrayNumber][4], 0F, 0F, 0F);
				sphere[arrayNumber][5] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][5].addBox(-7F, 15F + offset, 3F, 1, 1, 2);
				sphere[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][5].setTextureSize(64, 32);
				sphere[arrayNumber][5].mirror = true;
				setRotation(sphere[arrayNumber][5], 0F, 0F, 0F);
				sphere[arrayNumber][6] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][6].addBox(-6F, 15F + offset, 5F, 1, 1, 1);
				sphere[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][6].setTextureSize(64, 32);
				sphere[arrayNumber][6].mirror = true;
				setRotation(sphere[arrayNumber][6], 0F, 0F, 0F);
				sphere[arrayNumber][7] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][7].addBox(-5F, 15F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][7].setTextureSize(64, 32);
				sphere[arrayNumber][7].mirror = true;
				setRotation(sphere[arrayNumber][7], 0F, 0F, 0F);
				sphere[arrayNumber][8] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][8].addBox(-3F, 15F + offset, 7F, 6, 1, 1);
				sphere[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][8].setTextureSize(64, 32);
				sphere[arrayNumber][8].mirror = true;
				setRotation(sphere[arrayNumber][8], 0F, 0F, 0F);
				sphere[arrayNumber][9] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][9].addBox(3F, 15F + offset, 6F, 2, 1, 1);
				sphere[arrayNumber][9].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][9].setTextureSize(64, 32);
				sphere[arrayNumber][9].mirror = true;
				setRotation(sphere[arrayNumber][9], 0F, 0F, 0F);
				sphere[arrayNumber][10] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][10].addBox(5F, 15F + offset, 5F, 1, 1, 1);
				sphere[arrayNumber][10].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][10].setTextureSize(64, 32);
				sphere[arrayNumber][10].mirror = true;
				setRotation(sphere[arrayNumber][10], 0F, 0F, 0F);
				sphere[arrayNumber][11] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][11].addBox(6F, 15F + offset, 3F, 1, 1, 2);
				sphere[arrayNumber][11].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][11].setTextureSize(64, 32);
				sphere[arrayNumber][11].mirror = true;
				setRotation(sphere[arrayNumber][11], 0F, 0F, 0F);
				sphere[arrayNumber][12] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][12].addBox(7F, 15F + offset, -3F, 1, 1, 6);
				sphere[arrayNumber][12].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][12].setTextureSize(64, 32);
				sphere[arrayNumber][12].mirror = true;
				setRotation(sphere[arrayNumber][12], 0F, 0F, 0F);
				sphere[arrayNumber][13] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][13].addBox(6F, 15F + offset, -5F, 1, 1, 2);
				sphere[arrayNumber][13].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][13].setTextureSize(64, 32);
				sphere[arrayNumber][13].mirror = true;
				setRotation(sphere[arrayNumber][13], 0F, 0F, 0F);
				sphere[arrayNumber][14] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][14].addBox(5F, 15F + offset, -6F, 1, 1, 1);
				sphere[arrayNumber][14].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][14].setTextureSize(64, 32);
				sphere[arrayNumber][14].mirror = true;
				setRotation(sphere[arrayNumber][14], 0F, 0F, 0F);
				sphere[arrayNumber][15] = new ModelRenderer(this, 0, 0);
				sphere[arrayNumber][15].addBox(3F, 15F + offset, -7F, 2, 1, 1);
				sphere[arrayNumber][15].setRotationPoint(0F, 0F, 0F);
				sphere[arrayNumber][15].setTextureSize(64, 32);
				sphere[arrayNumber][15].mirror = true;
				setRotation(sphere[arrayNumber][15], 0F, 0F, 0F);
				
				liquid[arrayNumber] = new ModelRenderer[10];
				liquid[arrayNumber][0] = new ModelRenderer(this, 24, texOffset);
				liquid[arrayNumber][0].addBox(-5F, 16F + offset, -5F, 10, 1, 10);
				liquid[arrayNumber][0].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][0].setTextureSize(64, 128);
				liquid[arrayNumber][0].mirror = true;
				setRotation(liquid[arrayNumber][0], 0F, 0F, 0F);
				liquid[arrayNumber][1] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][1].addBox(-7F, 16F + offset, -3F, 1, 1, 6);
				liquid[arrayNumber][1].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][1].setTextureSize(64, 128);
				liquid[arrayNumber][1].mirror = true;
				setRotation(liquid[arrayNumber][1], 0F, 0F, 0F);
				liquid[arrayNumber][2] = new ModelRenderer(this, 30, texOffset);
				liquid[arrayNumber][2].addBox(6F, 16F + offset, -3F, 1, 1, 6);
				liquid[arrayNumber][2].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][2].setTextureSize(64, 128);
				liquid[arrayNumber][2].mirror = true;
				setRotation(liquid[arrayNumber][2], 0F, 0F, 0F);
				liquid[arrayNumber][3] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][3].addBox(-3F, 16F + offset, -7F, 6, 1, 1);
				liquid[arrayNumber][3].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][3].setTextureSize(64, 128);
				liquid[arrayNumber][3].mirror = true;
				setRotation(liquid[arrayNumber][3], 0F, 0F, 0F);
				liquid[arrayNumber][4] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][4].addBox(-3F, 16F + offset, 6F, 6, 1, 1);
				liquid[arrayNumber][4].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][4].setTextureSize(64, 128);
				liquid[arrayNumber][4].mirror = true;
				setRotation(liquid[arrayNumber][4], 0F, 0F, 0F);
				liquid[arrayNumber][5] = new ModelRenderer(this, 33, texOffset);
				liquid[arrayNumber][5].addBox(-5F, 16F + offset, 5F, 10, 1, 1);
				liquid[arrayNumber][5].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][5].setTextureSize(64, 128);
				liquid[arrayNumber][5].mirror = true;
				setRotation(liquid[arrayNumber][5], 0F, 0F, 0F);
				liquid[arrayNumber][6] = new ModelRenderer(this, 40, texOffset);
				liquid[arrayNumber][6].addBox(-5F, 16F + offset, -6F, 10, 1, 1);
				liquid[arrayNumber][6].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][6].setTextureSize(64, 128);
				liquid[arrayNumber][6].mirror = true;
				setRotation(liquid[arrayNumber][6], 0F, 0F, 0F);
				liquid[arrayNumber][7] = new ModelRenderer(this, 27, texOffset);
				liquid[arrayNumber][7].addBox(-6F, 16F + offset, -5F, 1, 1, 10);
				liquid[arrayNumber][7].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][7].setTextureSize(64, 128);
				liquid[arrayNumber][7].mirror = true;
				setRotation(liquid[arrayNumber][7], 0F, 0F, 0F);
				liquid[arrayNumber][8] = new ModelRenderer(this, 32, texOffset);
				liquid[arrayNumber][8].addBox(5F, 16F + offset, -5F, 1, 1, 10);
				liquid[arrayNumber][8].setRotationPoint(0F, 0F, 0F);
				liquid[arrayNumber][8].setTextureSize(64, 128);
				liquid[arrayNumber][8].mirror = true;
				setRotation(liquid[arrayNumber][8], 0F, 0F, 0F);
				break;
			default:
				break;
		}
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3,
			float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
