// Date: 23.09.2014 14:26:12
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package de.teamlapen.vampirism.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelBloodAltarTier4 extends ModelBase {
	//fields
    ModelRenderer base1;
    ModelRenderer base2;
    ModelRenderer pillar1;
    ModelRenderer pillar2;
    ModelRenderer pillar3;
    ModelRenderer pillar4;
    ModelRenderer top;
    ModelRenderer middle;
    ModelRenderer platform;
    ModelRenderer middlePillar;
    ModelRenderer topPillar1;
    ModelRenderer topPillar2;
    ModelRenderer topPillar3;
    ModelRenderer topPillar4;
  
  public ModelBloodAltarTier4()
  {
	    textureWidth = 128;
	    textureHeight = 64;
    
      base1 = new ModelRenderer(this, 0, 23);
      base1.addBox(-8F, 0F, -2F, 16, 6, 4);
      base1.setRotationPoint(0F, 18F, 0F);
      base1.setTextureSize(128, 64);
      base1.mirror = true;
      setRotation(base1, 0F, 0F, 0F);
      base2 = new ModelRenderer(this, 0, 33);
      base2.addBox(-2F, 0F, -8F, 4, 6, 16);
      base2.setRotationPoint(0F, 18F, 0F);
      base2.setTextureSize(128, 64);
      base2.mirror = true;
      setRotation(base2, 0F, 0F, 0F);
      pillar1 = new ModelRenderer(this, 65, 0);
      pillar1.addBox(-8F, -6F, 6F, 2, 6, 2);
      pillar1.setRotationPoint(0F, 17F, 0F);
      pillar1.setTextureSize(128, 64);
      pillar1.mirror = true;
      setRotation(pillar1, 0F, 0F, 0F);
      pillar2 = new ModelRenderer(this, 65, 0);
      pillar2.addBox(-8F, -6F, -8F, 2, 6, 2);
      pillar2.setRotationPoint(0F, 17F, 0F);
      pillar2.setTextureSize(128, 64);
      pillar2.mirror = true;
      setRotation(pillar2, 0F, 0F, 0F);
      pillar3 = new ModelRenderer(this, 65, 0);
      pillar3.addBox(6F, -6F, -8F, 2, 6, 2);
      pillar3.setRotationPoint(0F, 17F, 0F);
      pillar3.setTextureSize(128, 64);
      pillar3.mirror = true;
      setRotation(pillar3, 0F, 0F, 0F);
      pillar4 = new ModelRenderer(this, 65, 0);
      pillar4.addBox(6F, -6F, 6F, 2, 6, 2);
      pillar4.setRotationPoint(0F, 17F, 0F);
      pillar4.setTextureSize(128, 64);
      pillar4.mirror = true;
      setRotation(pillar4, 0F, 0F, 0F);
      top = new ModelRenderer(this, 74, 0);
      top.addBox(-3F, -10F, -3F, 6, 0, 6);
      top.setRotationPoint(0F, 17F, 0F);
      top.setTextureSize(128, 64);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      middle = new ModelRenderer(this, 45, 20);
      middle.addBox(-8F, -6F, -8F, 16, 0, 16);
      middle.setRotationPoint(0F, 17F, 0F);
      middle.setTextureSize(128, 64);
      middle.mirror = true;
      setRotation(middle, 0F, 0F, 0F);
      platform = new ModelRenderer(this, 0, 0);
      platform.addBox(-8F, 0F, -8F, 16, 1, 16);
      platform.setRotationPoint(0F, 17F, 0F);
      platform.setTextureSize(128, 64);
      platform.mirror = true;
      setRotation(platform, 0F, 0F, 0F);
      middlePillar = new ModelRenderer(this, 75, 8);
      middlePillar.addBox(-1.5F, -8F, -1.5F, 3, 8, 3);
      middlePillar.setRotationPoint(0F, 17F, 0F);
      middlePillar.setTextureSize(128, 64);
      middlePillar.mirror = true;
      setRotation(middlePillar, 0F, 0F, 0F);
      topPillar1 = new ModelRenderer(this, 0, 17);
      topPillar1.addBox(-0.5F, -10F, -3F, 1, 4, 1);
      topPillar1.setRotationPoint(0F, 17F, 0F);
      topPillar1.setTextureSize(128, 64);
      topPillar1.mirror = true;
      setRotation(topPillar1, 0F, 0F, 0F);
      topPillar2 = new ModelRenderer(this, 0, 17);
      topPillar2.addBox(2F, -10F, -0.5F, 1, 4, 1);
      topPillar2.setRotationPoint(0F, 17F, 0F);
      topPillar2.setTextureSize(128, 64);
      topPillar2.mirror = true;
      setRotation(topPillar2, 0F, 0F, 0F);
      topPillar3 = new ModelRenderer(this, 0, 17);
      topPillar3.addBox(-0.5F, -10F, 2F, 1, 4, 1);
      topPillar3.setRotationPoint(0F, 17F, 0F);
      topPillar3.setTextureSize(128, 64);
      topPillar3.mirror = true;
      setRotation(topPillar3, 0F, 0F, 0F);
      topPillar4 = new ModelRenderer(this, 0, 17);
      topPillar4.addBox(-3F, -10F, -0.5F, 1, 4, 1);
      topPillar4.setRotationPoint(0F, 17F, 0F);
      topPillar4.setTextureSize(128, 64);
      topPillar4.mirror = true;
      setRotation(topPillar4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    base1.render(f5);
    base2.render(f5);
    pillar1.render(f5);
    pillar2.render(f5);
    pillar3.render(f5);
    pillar4.render(f5);
    top.render(f5);
    middle.render(f5);
    platform.render(f5);
    middlePillar.render(f5);
    topPillar1.render(f5);
    topPillar2.render(f5);
    topPillar3.render(f5);
    topPillar4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,e);
  }

}
