@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package de.teamlapen.vampirism.fluids;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;