@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package de.teamlapen.vampirism.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;