@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package de.teamlapen.vampirism.client.extensions;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;