plugins {
    id 'net.neoforged.moddev' version '2.0.141'
}

group = project.factions_group_id
version = project.mod_version

base {
    archivesName = "${project.factions_mod_name}-api"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.java_version)
    }
    withSourcesJar()
}

neoForge {
    version = project.neoforge_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    javaToolchains {
        compilerFor {
            languageVersion = JavaLanguageVersion.of(project.java_version)
        }
    }
}
