plugins {
    id 'net.neoforged.moddev' version '2.0.141'
}

group = project.vampirism_group_id
version = project.vampirism_version

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(project.java_version)
    }
    withSourcesJar()
}

neoForge {
    version = project.neoforge_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    javaToolchains {
        compilerFor{
            languageVersion = JavaLanguageVersion.of(project.java_version)
        }
    }
}

apply from: file('dependencies.gradle')

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            it.artifactId = "${project.vampirism_mod_name}-api"
        }
    }
}