name: Gradle Build

on:
  push:
    branches:
      - 'dev'
      - 'feature/*'
      - 'version/*'
  pull_request:
    branches:
      - 'dev'
      - 'feature/*'
      - 'version/*'
      - 'translate/*'

jobs:
  build:
    strategy:
      matrix:
        project: ['faction', 'vampirism']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        run: ./gradlew
      - name: Build API
        run: ./gradlew ${{ matrix.project }}-api:build
      - name: Build Mod
        run: ./gradlew ${{ matrix.project }}:build

