name: publish.yml
on:
  push:
    tags:
      - '*-alpha.*'
      - '*-beta.*'
  release:
    types:
      - published

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      mc_version: ${{ steps.extract.outputs.mc_version }}
      mod_version: ${{ steps.extract.outputs.mod_version }}
    steps:
      - name: Extract mod version from tag
        id: extract
        run: |
          echo "mc_version=${GITHUB_REF_NAME%%-*}" >> $GITHUB_OUTPUT
          echo "mod_version=${GITHUB_REF_NAME#*-}" >> $GITHUB_OUTPUT

  build:
    needs: [ prepare ]
    strategy:
      matrix:
        project: [ 'faction', 'vampirism' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        run: ./gradlew -Pmod_version=${{ needs.prepare.outputs.mod_version }}
      - name: Build API
        run: ./gradlew ${{ matrix.project }}-api:build -Pmod_version=${{ needs.prepare.outputs.mod_version }}
      - name: Build Mod
        run: ./gradlew ${{ matrix.project }}:build -Pmod_version=${{ needs.prepare.outputs.mod_version }}
      - name: Upload Jars
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.project }}-jars
          path: |
            projects/${{ matrix.project }}/build/libs/*.jar
            projects/${{ matrix.project }}-api/build/libs/*.jar
          retention-days: 2

  publish-maven:
    needs: [ prepare, build ]
    strategy:
      matrix:
        project: [ 'faction', 'vampirism' ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Setup Gradle
        run: ./gradlew -Pmod_version=${{ needs.prepare.outputs.mod_version }}
      - name: Publish to Maven
        run: ./gradlew ${{ matrix.project }}-api:publish ${{ matrix.project }}:publish -Pmod_version=${{ needs.prepare.outputs.mod_version }}
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  publish-curseforge:
    needs: [ prepare, build, publish-maven ]
    strategy:
      matrix:
        include:
          - project: vampirism
            cf_id: '233029'
            modrinth_id: jVZ0F1wn
            jar_base: Vampirism
          - project: faction
            cf_id: '1416927'
            modrinth_id: uYW0To9A
            jar_base: FactionAPI
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifacts
        uses: actions/download-artifact@v6
        with:
          name: ${{ matrix.project }}-jars
          path: jars/
      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: ${{ matrix.cf_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          modrinth-id: ${{ matrix.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          files: jars/projects/${{ matrix.project }}/build/libs/${{ matrix.jar_base }}-${{ needs.prepare.outputs.mod_version }}.jar
          name: ${{ matrix.jar_base }} ${{ needs.prepare.outputs.mod_version }}
          version: ${{ needs.prepare.outputs.mod_version }}
          version-type: ${{ contains(needs.prepare.outputs.mod_version, 'alpha') && 'alpha' || contains(needs.prepare.outputs.mod_version, 'beta') && 'beta' || 'release' }}
          changelog: ${{ github.event.release.body }}
#          game-versions: |
#            ${{ needs.prepare.outputs.mc_version }}
#          loaders: |
#            neoforge