name: Update API

on:
  push:
    paths:
      - '**/src/main/resources/supporters.json'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.ref_name == 'dev'
    steps:
      - uses: actions/checkout@v4
      - name: Upload supporters
        env:
          API_URL: https://api.vampirism.dev/api/v2/supporter/vampirism
          API_KEY: ${{ secrets.VAMPIRISM_API }}
          JSON_FILE: projects/vampirism/src/main/resources/supporters.json
        run: |
          curl -X 'PUT' "$API_URL" -H 'Authorization: Bearer $API_KEY' -H 'Content-Type: application/json' --upload-file $JSON_FILE